name: PHP Laravel CI

# Trigger the workflow on push to the main branch and pull requests
on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository code
      - uses: actions/checkout@v2

      # Set up PHP with the desired version
      - name: Set up PHP 8.0
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'  # Change to 8.0 or any higher version
          extensions: mbstring, intl, gd  # Add any required PHP extensions

      # Install Composer (PHP dependency manager)
      - name: Install Composer
        run: curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

      # Install dependencies
      - name: Install dependencies
        run: composer install --no-interaction

      # Create the SQLite database for testing
      - name: Create Database
        run: |
          mkdir -p database
          touch database/database.sqlite

      # Set environment variables for SQLite (adjust for your DB if necessary)
      - name: Set environment variables
        run: |
          echo "DB_CONNECTION=sqlite" >> .env
          echo "DB_DATABASE=database/database.sqlite" >> .env

      # Generate Laravel key
      - name: Generate key
        run: php artisan key:generate

      # Set directory permissions
      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache

      # Run the tests
      - name: Execute tests (Unit and Feature tests) via PHPUnit
        run: vendor/bin/phpunit
